version: '3'
services:
  web:
    container_name: solution-manager
    build: ./Resolute.ChatHub
    labels:
        SERVICE_80_NAME: solution-manager
        SERVICE_TAG: solutionmanager
    depends_on:
      - db
  db:
    image: mvertes/alpine-mongo
    volumes:
        - "/data/solution-manager:/var/lib/mongodb"