version: '3'
services:
  web:
    container_name: Resolute-Solution-Manager
    build: ./Resolute.ChatHub
    labels:
        SERVICE_80_NAME: Resolute-Solution-Manager
        SERVICE_TAG: ResoluteSolutionManager
    depends_on:
      - db
  db:
    image: mvertes/alpine-mongo
    volumes:
        - "/data/solution-manager:/var/lib/mongodb"